---
# 1. Check if Helm is installed
- name: Check if Helm is installed
  command: helm version --short
  ignore_errors: yes
  register: helm_installed
  changed_when: false

# 1.1 Install Helm if not installed
- name: Install Helm if not installed
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  when: helm_installed.rc != 0
  ignore_errors: yes

# 2. Check if artifactory repository is added
- name: Check if Artifactory repository is added
  shell: helm search repo jfrog
  register: helm_repo_exists
  ignore_errors: yes

# 2.1 Add artifactory repository if it does not exist
- name: Add Artifactory Helm repository
  command: helm repo add jfrog https://charts.jfrog.io
  when: helm_repo_exists.failed

# 2.2 Update artifactory repository if it exists
- name: Update Artifactory Helm repository
  command: helm repo update jfrog
  when: helm_repo_exists

# 3. Create kubectl namespace if not exists using kubernetes.core.k8s
- name: Create Namespace if it doesn't exist
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
    state: present

# 4. Check if artifactory release exists
- name: Check if artifactory {{ artifactory_instance }} deployed or not
  shell: "helm status -n {{ namespace }} {{ artifactory_instance }}"
  register: helm_chart_exists
  ignore_errors: yes

# 4.1 Install artifactory chart
- name: Deploy Artifactory {{ artifactory_instance }}
  kubernetes.core.helm:
    release_name: "{{ artifactory_instance }}"
    release_state: "present"
    chart_ref: jfrog/artifactory-oss
    chart_version: "{{ artifactory_chart_version }}"
    namespace: "{{ namespace }}"
    values_files:
      - "{{ values_file }}"
  register: helm_install
  retries: 3
  delay: 30
  until: helm_install is succeeded
  when: helm_chart_exists.failed and action == "install"


# 4.2 Upgrade artifactory chart
- name: Upgrade Artifactory {{ artifactory_instance }}
  kubernetes.core.helm:
    release_name: "{{ artifactory_instance }}"
    release_state: "present"
    chart_ref: jfrog/artifactory-oss
    chart_version: "{{ artifactory_chart_version }}"
    namespace: "{{ namespace }}"
    values_files:
      - "{{ values_file }}"
  register: helm_upgrade
  retries: 3
  delay: 30
  until: helm_upgrade is succeeded
  when: helm_chart_exists.rc == 0 and action == "upgrade"

# 4.3 Remove artifactory chart
- name: Uninstall Artifactory {{ artifactory_instance }}
  kubernetes.core.helm:
    release_name: "{{ artifactory_instance }}"
    release_state: "absent"
    namespace: "{{ namespace }}"
    values_files:
      - "{{ values_file }}"
  register: helm_uninstall
  retries: 3
  delay: 30
  until: helm_uninstall is succeeded
  when: helm_chart_exists.rc == 0 and action == "uninstall"