name: Deploy Monitoring

on: workflow_dispatch

jobs:
  terraform:
    name: 'Deploy Terraform'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init -var "client_id=${{ secrets.ARM_CLIENT_ID }}" -var "client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var "tenant_id=${{ secrets.ARM_TENANT_ID }}" -var "admin_username=${{ secrets.ADMIN_USERNAME }}" -var "admin_password=${{ secrets.ADMIN_PASSWORD }}"
        working-directory: ./terraform/main

      - name: Terraform Plan
        run: terraform plan -var "client_id=${{ secrets.ARM_CLIENT_ID }}" -var "client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var "tenant_id=${{ secrets.ARM_TENANT_ID }}" -var "admin_username=${{ secrets.ADMIN_USERNAME }}" -var "admin_password=${{ secrets.ADMIN_PASSWORD }}"
        working-directory: ./terraform/main

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "client_id=${{ secrets.ARM_CLIENT_ID }}" -var "client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var "tenant_id=${{ secrets.ARM_TENANT_ID }}" -var "admin_username=${{ secrets.ADMIN_USERNAME }}" -var "admin_password=${{ secrets.ADMIN_PASSWORD }}"
        working-directory: ./terraform/main
