- name: Check if Java is installed
  win_reg_stat:
    path: HKLM:\SOFTWARE\JavaSoft
  register: java_installed
  changed_when: no

- name: Download Java 17
  win_get_url:
    url: "https://download.oracle.com/java/{{ java_ver.split('.')[0] }}/archive/jdk-{{ java_ver }}_windows-x64_bin.exe"
    dest: C:\temp\java.exe
  when: not java_installed.exists

- name: Install Java 17
  win_command:
    argv:
      - C:\temp\java.exe
      - /s
  when: not java_installed.exists

- name: Check if Jenkins is installed
  win_reg_stat:
    path: HKLM:\SOFTWARE\Jenkins
  register: jenkins_installed
  changed_when: no

- name: Download Jenkins
  win_get_url:
    url: "https://get.jenkins.io/windows-stable/{{ jenkins_ver }}/jenkins.msi"
    dest: C:\temp\jenkins.msi
  when: not jenkins_installed.exists

- name: Setup Jenkins
  ansible.windows.win_powershell:
    script: |
      Start-Process -Wait msiexec.exe -ArgumentList '/i','C:\temp\jenkins.msi','/quiet','/norestart','JAVA_HOME="C:\Program Files\Java\jdk-17"','SERVICE_USERNAME="NT AUTHORITY\SYSTEM"'
  when: not jenkins_installed.exists
