apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
  namespace: demoapp
spec:
  replicas: {{ .Values.demoapp.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: demoapp-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demoapp-service
    spec:
      serviceAccountName: podprobe
      containers:
      - name: demoapp-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        resources:
          {{- toYaml .Values.demoapp.resources | nindent 12 }}
