apiVersion: v1
kind: Service
metadata:
  name: demoapp-service
  namespace: demoapp
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: demoapp-service
